
#include "sk6812.h"


uint32_t BUF_DMA [ARRAY_LEN] = {0};

/*
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0XWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0XWNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXWWKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXWWNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWWXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKNMNKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWWNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKKKKKKKXWMNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KNMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00XW
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,c0WO:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:OW0c,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:0W0c,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;kWKl,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;dNXd,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;xNXOo,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dXNd;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,lKW0olllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllkNWOolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldXWKolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloKWKdllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNKc...............................................................oNXl.............................................................'dNKOc...............................................................lXNo...............................................................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdXNOcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKoccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccco0
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNKc..............................................................'oNXl.............................................................'dNKOc...............................................................lXNo'..............................................................:KWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdXNOcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNKc..............................................................'oNXl.............................................................'dNKOc...............................................................lXNo'..............................................................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccxXWOcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;........................................''....................,xNKc.....................................''.......................'oNXl.....................................'''.....................'dNKOc...............................................................lXNo'....................................'''.......................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccxXNOcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
..................';loooool:,'..':ooooooooooc,.................:0Wk,.................':ooooolc:,........,clc,'....................,kW0:..................;looooll:,'....':oodooooc,.................;OWO;..................':loooolc:,........':oxxl,..................,xNKc..................,cooooolc;'....':ldxxdl;'...................'oNXl..................,coooool:;'....,:odxxdl;'..................'dNKOc..................';loooool:,'....,coooo:,.....................lXNo'.................':loooolc:,'...';cdxxxo:,....................cKWOlccccccccccccccccclodkOOOOOkdolccccoxkkkkkkkkkxolcccccccccccccdXWOcccccccccccccccccccloxkOOOOOkdoccccccccccoxxolcccccccccccccccccoKW0lccccccccccccccccccloxkOOOOkxdlccccccclxkkkkkkxocccccccccccccccl0WKoccccccccccccccccccldxkOOOOkxolcccccccccclxO0kdlccccccccccccccoK
..................,oKNWNXNNXOl,.,oKXXXXNNWWXk:'................:0Wk,.................,dXWNNXNNKkc'.....,oKNOl'....................,kW0:.................'oKNNNXNNXOl,..':kNWNXXXXk:'................;OWO;..................,dXWNNXXXKkc'.....,l0NWNk:'.................,xNKc..................;kNWNNXNNKx:..;dKNXXXNX0l,..................'oNXl..................:ONWNNNNX0o;.':xXNXXXNN0o,.................'dNKOc..................'l0WNNNNNXOl,..,o0XNNXk:.....................lXNo'.................,dXWNNXNNXkc'.,l0XNXXNNXk:'..................cKWOlcccccccccccccccldOXNNNNXNNNNX0dlccd0NNNNNNWWWXklcccccccccccccxXNOccccccccccccccccclx0XNNNNXNNNNXOdcccccccd0NNOocccccccccccccccccoKW0lccccccccccccccccox0XNNNXXNNNNKkocccclkXWWNNNNKklccccccccccccccl0WKoccccccccccccccccokKNNNNXXNNNXKklcccccccoONWWXklccccccccccccccoK
..................,oXWXxclkXW0c'',:cccco0WN0l'.................:0Wk,.................,dNWKdco0NNO:....,oKNKo,.....................,kW0:.................'oXWXxclONN0c'.,oKWKdccc:;'.................;OWO;..................;xXWKdcoONNk:...';dXWMMWO:'.................,xNKc..................:ONW0ocd0WNx,':dOxl:lkNNO:'.................'oNXl..................:0WNOlcxXNXo,;kNNOl:cxXWKo,................'dNKOc..................'lKWXxllkXW0l'.';:lOWNk:.....................lXNo'.................,dXWXdcoONWO:,lKWXxc:lONNk:..................cKWOlccccccccccccccoOXWNKkdooodk0K0xlccloddddx0NWNOoccccccccccccccxXNOccccccccccccccccdONWX0kdooddk0K0dccccccd0NN0dccccccccccccccccccoKW0lccccccccccccccld0NWX0xdoodxOKKOocccco0NN0xddddlcccccccccccccccl0WKocccccccccccccclxKNNXOxdoodxOKKkoccccclxKWWMMNklccccccccccccccoK
..................,oXWXo;:xXW0c'......;xXN0l'..................:0Wk,.................,dNN0l;ckNNO:...,oKWXd;'.....................,kW0:.................'oXWKd::xXWKc..;kNWKxl:;'...................;OWO;..................;xXW0l;ckNNO:..'cONWXXWNO:'.................,xNKc..................:ONNOc;lONNx;''''';cd0NXx;'.................'oNXl..................:0WXx:;oKNXd,,ldo:'.'cKWKo,................'dNKOc..................'lKWKd::dXWKo'....,xNNk:.....................lXNo'.................,dXWKl;ckXWOc:kNNO:..'lKWKl'.................cKWOlccccccccccccclONWXkoccccccclllccccccccclxKWNOocccccccccccccccdXNOcccccccccccccccoONWKxlccccccclllccccccd0NWKxlccccccccccccccccccoKW0lccccccccccccccdKNW0dlccccccclllcccclxXWN0kdolcccccccccccccccccl0WKoccccccccccccclxXWNOolcccccclllccccccokXWNXNWNklccccccccccccccoK
..................'oXWWXKXNN0o,......;dXN0l,...................:0Wk,.................,xNWNXKXNNOl,..,dKWWNKOd:'...................,kW0:.................'oXWWXKXNN0o;.'c0WWNNNX0d;'.................;OWO;..................;dXWNXKXNNOl,.,oKWXklxNNO:'.................,xNKc..................:ONWNXXXNXkc'....,o0WWNOc'..................'oNXl..................:0WWNXKNNKx:'......'cONNk:'................'dNKOc..................'lKWWXKXNNKd;.....,xNNk:.....................lXNo'.................,dXWWXKXNN0o,:OWXx;..'cOWXd,.................cKWOlcccccccccccccd0WN0occccloooooooolccccclxKWNOoccccccccccccccccdXNOcccccccccccccclxXWNklcccclooooooollccdKWMWNK0xoccccccccccccccccoKW0lccccccccccccclkNWXxccccclooooooolccoONWWWNNX0xlcccccccccccccccl0WKoccccccccccccclONWKdccccloooooooolcld0NWXOkKWXklccccccccccccccoK
..................,oXWWNNWNk:'......;dXN0l,....................:0Wk,.................,xNWNNWWXx;'..,oKWN0O0XNKo,..................,kW0:.................'oXWNNWWNk:'..':dkkdoxKNNx;'................;OWO;..................;dXWNNWWXx:'.;xXWXx::xNNOc'.................,xNKc..................:ONWNNWWKo;'.....':ox0NN0l,.................'oNXl..................:0WWNNWW0l,......':dKNXx:'.................'dNKOc..................'lKWWNWWNkc'......,kNNk:.....................lXNo'.................,dXWWNWWXx:'':OWXx;..'cOWXd,.................cKWOlcccccccccccccd0WNOoccclkKXXXXXXKxlccclxKWNOocccccccccccccccccdXNOcccccccccccccclxXWNklcccoOKXXXXNX0dld0NWXKKXWN0dcccccccccccccccoKW0lccccccccccccclkNWXxccccd0XXXXXXXOocox00Okk0NWXxlccccccccccccccl0WKoccccccccccccclONWKdccccd0XXXXNNKkdxKWWKxoxKWNklccccccccccccccoK
..................,oXWXxkNNOc'.....;dXN0l,.....................:0Wk,.................,xNN0k0NNk:'..cONNx;';xNNOc'.................,kW0:.................'oXWKkOXNOc'..'',,'..'oXW0l'................;OWO;..................,xXW0x0NNk:''lKWMNK0KXWWNOl,................,xNKc..................:ONW0x0NXx;..,:c:,'.':kNWO:.................'oNXl..................:0WXOkKWKo,....':dKNXOl,...................'dNKOc..................'lKWKxOXN0l'......,xNNk:.....................lXNo'.................,dXWKxONNOc'.;kWNk:..'lKWKo'.................cKWOlccccccccccccclONWXklccldO00KNWWKxlcccdKWN0occccccccccccccccccdXNOcccccccccccccccoONWKxlcclxO00XWMW0olkNWXxllxKWNklccccccccccccccoKW0lccccccccccccccdKNW0dlccokO00XWWNOocclllcccd0WNOoccccccccccccccl0WKoccccccccccccccxXWNOocccokO0KNWMXkd0WMWNXXXWMWXOocccccccccccccoK
..................'oXWKl:kNNOc'...;dXNKo,......................:0Wk,.................,dNNOccONNk:'.:ONNOc;ckNNO:'.................,kW0:.................'oXWKockXN0c',cxkdl;;ckNNk:'................;OWO;..................;dXWOccONNk:':xOOOOO0XWWXOc'................,xNKc..................:ONNk:l0WXx;':kXXkl;;lONNk;.................'oNXl..................:0WXd:dKNKo,.';dKWWXOoc::,'................'dNKOc..................'lKWKocxXN0l'.....,xNNk:.....................lXNo'.................,dXW0cckNNOc',oKWXd:;lONNO:..................cKWOlccccccccccccccoOXWN0kdooodkKNWXxlcccdKNN0occcccccccccccccccccdXNOccccccccccccccccd0NWN0xdolodkKWWKxllkXWXkodkXWXklccccccccccccccoKW0lccccccccccccccldKNWXOxoloodOXWN0dlok0OkdodkXWXklccccccccccccccl0WKocccccccccccccclkKWNKOxoloox0XWNOolx0KKKKKXWMWXkocccccccccccccoK
..................'oXWKl';xXN0l'.'l0NKo,.......................:0Wk,.................,dNNOc':ONNkc''ckXNXKXNXOc'..................,kW0:.................'oXN0l,;xXN0l,:kXNNKKXNKkc'.................;OWO;..................;dXWO:,cONNkc'',,,,,:xNNOc'.................,xNKc..................:kNNk;'l0NXx;,cOXNXKKXNXk:'.................'oNXl..................:0WXd,,oKNKd:lONWMWNXXXX0d;................'dNKOc..................'lKWKl,;xXN0l,....,xNNk:.....................lXNo'.................,dXN0c':kNNOc',o0NNXKXNXkc'..................cKWOlccccccccccccccclx0XNWNXXXNNNXOdlcccoONN0occccccccccccccccccccdXNOcccccccccccccccccox0XNNNXXXNNNKOocccokXNNXNNNXOocccccccccccccccoKW0lccccccccccccccccokKNWNNXXXNNNKkocclkKNWNXNNNKklcccccccccccccccl0WKocccccccccccccccldOKNWNXXXXNNX0xlcccllllloxKWNkoccccccccccccccoK
..................';lol;.',ldoc'.';coc,........................:0Wk,.................':ooc,.':ldo:'.',cdxkxdc,'...................,kW0:..................;ool;..;ldo:'',:oxkkxoc,...................;OWO;..................':ooc,.';odo:'......':ooc,..................,xNKc..................,cooc'.':odl;'',cdxkkxo:,...................'oNXl..................,ldo:'.,cooc:codddddddddoc'................'dNKOc..................';ldl;'.,looc,....':ooc,.....................lXNo'.................':ool,.';ldo:'.':lxkkxdc,'...................cKWOlcccccccccccccccccloxkO000OkxolcccccldxxocccccccccccccccccccccdXNOcccccccccccccccccccloxkO000OkxoccccccloxO00OxolccccccccccccccccoKW0lccccccccccccccccccldkOO000OkdlccccccoxkO0OOxocccccccccccccccccl0WKoccccccccccccccccccodkOO00OOxdlccccccccccclxkxocccccccccccccccoK
...............................................................:0Wk,....................................'''.......................,kW0:....................................''.......................;OWO;..............................................................,xNKc....................................''''......................'oNXl.............................................................'dNKOc...............................................................lXNo'....................................'''.......................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdXWOccccccccccccccccccccccccclcccccccccccccccccccccccccccccccccccccoKW0lcccccccccccccccccccccccccccccccccccccccclcccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNKc..............................................................'oNXl.............................................................'dNKOc...............................................................lXNo'..............................................................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccxXNkcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNKc..............................................................'oNXl.............................................................'dNKOc...............................................................lXNo'..............................................................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccxXNkcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNKc..............................................................'oNXl.............................................................'dNKOc...............................................................lXNo'..............................................................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdXNOcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
...............................................................:0Wk,..............................................................,kW0:.............................................................;OWO;..............................................................,xNK:..............................................................'oNXl.............................................................'dNKOc...............................................................lXNo'..............................................................cKWOlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccxXWOcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoK
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxONWXkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkXWNOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOXWXOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkKWNOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxKWW0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkKWNX0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0WWKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxONMX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWWX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKNMN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NWNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0N
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNMNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNMN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWWKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXWWNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWWKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NMXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWWXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NMN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NMN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0N
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdKW0occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccco0WKdcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKoccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WK:...............................................................oNXl.............................................................'dWXOc...............................................................lXNo...............................................................:KWx'.............................................................cXWd'..............................................................:0Wk,..............................................................,kW0;.............................................................;O
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXkc...............................................................lXNo...............................................................:KWx'.............................................................cXWd...............................................................;0Wk,..............................................................,kW0;.............................................................,O
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXOc...............................................................lXNo...............................................................:KWx'.............................................................cXWd...............................................................;0Mk'..............................................................,kW0;.............................................................,O
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXOc...............................................................lXNo...............................................................:KWx'.............................................................cXWd...............................................................;0Mk'..............................................................,kW0;.............................................................,O
ccccccccccccccccccccccclllllccccccccccccclllcccccccccccccccccccoKW0lcccccccccccccccccccccclllllccccccccccccclllcccccccccccccccccccl0WKoccccccccccccccccccccccllllcccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccllllccccccccccccclllccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXOc...............................................................lXNo........................................'''....................:KWx'....................................'''......................cXWd.....................................''''......................;0Mk'..............................................................,kW0;....................................'''......................,O
cccccccccccccccccccloxO0KKK0OkxoccccccoxO0K0OxoccccccccccccccccoKW0lccccccccccccccccccldkO0KKK0OkdlcccccldkO0K0Oxoccccccccccccccccl0WKoccccccccccccccccccldkO0KKK0OkdlccccccdkOOOkdcccccccccccccccccoKWKocccccccccccccccccccoxkO0KK00OxolcccccoxO0K0OxocccccccccccccccclOWK:..................,ldxxxdoc,....:oxxxxxxxxxo;..................oNXl..................,oxxxxdl:,........'cdo:'....................dWXOc...................;oxxxddl:'......:oxxxxxxo;..................lXNo..................'cdxxxdoc;'.........;dOOd;...................:KWx'.................'cdxxxdoc,.....':oxOOkdc,...................cXWd...................,lxxxxdo:,.....':dkOOkdc,...................;0Mk'..................;oxxxxdl:'.....'cdxxxl,.....................,kW0;..................:dxxxdol;'.....;lxOOOxl;'..................,O
cccccccccccccccccld0XNNXXKXXNNNKkocclxKNNXXNWNKxlccccccccccccccoKW0lcccccccccccccccclx0NNNXXKXXNWNKxlccokXNNXXXNWKxlccccccccccccccl0WKoccccccccccccccccokKNWNXXKXXNNN0dlcccdOXNWWXklccccccccccccccccoKWKocccccccccccccccccdOKNNNXXXXNNNXOocclxKNNXXXWNKxlcccccccccccccclOWK:..................:ONWNXXNNOc'.'lOKXXXXNWMWO:..................oNXl..................c0WWNXNNXk:......'l0NKl'....................dWXOc..................'oKWWNXNNKx;....;xXWNXXXXk:..................lXNo..................,dXWWXXNNKo,......'l0NMW0c...................:KWx'.................;kNWNXXNN0l'..,oKNXKKXWXx;..................cXWd...................:OWWNXXNXOc'..;xXNXKKXWNk:..................;0Mk'..................lKWWNXNNXx:...'ckXNWWO:.....................,kW0;.................'oXWWNXNNKd,..'l0NNXKXNN0l'.................,O
ccccccccccccccccokXWN0xoollodk00xlccldOOxooxKWNOoccccccccccccccoKW0lcccccccccccccccoONWXOxolllodO0OdlclxXNXkood0NWKdccccccccccccccl0WKoccccccccccccccld0NWXOdollloxO0OdccccllokXWNklccccccccccccccccoKWKoccccccccccccccclxKNNKkdollodk00koccxXWNOdodONWXxcccccccccccccclOWK:..................:ONNkccONNO:..',,,,,ckNW0l'..................oNXl..................c0WXxcl0WNx,....'lKWKo,.....................dWXOc..................'oKMKo:oKWXo'...c0NKd;,,,,...................lXNo..................,dXW0l:dXWKl.....;dXWWMM0c...................:KWx'.................;kWNOcckNWO:..;lddc,;dXWKl'.................cXWd...................:OWNx:lONNk,.,dXNOc,,l0WNx,.................;0Mk'..................lKWXd:l0WXd,...',:xXWO:.....................,kW0;.................'oXWKo:dKWKl'.c0WXx:,:dXWKl'................,O
ccccccccccccccclkXWXkoccccccccllccccccccldkKNNKxlccccccccccccccoKW0lccccccccccccccoONWXxlcccccccclcccccoxxdlccoONWKdccccccccccccccl0WKoccccccccccccccd0NWKdlcccccccclcccccccccdXWNklccccccccccccccccoKWKocccccccccccccccdKWN0dccccccccclccclONWKdcccdKWNOlccccccccccccclOWK:..................:ONWOllONXd,.......,dXN0l'...................oNXl..................c0WXklo0NKo'...'oKWNk:'.....................dWXOc..................'oKMXdlxXN0c...,dXWXkdl:,....................lXNo..................,dNWKockXNk:...'ckNNK0NW0c...................:KWx'.................;kWNOolONNx,......,cxKNXk;..................cXWd...................:OWNklo0NKd'.':lc;...:OWNd,.................;0Mk'..................lKWXxcdKW0l'.....'oXWO:.....................,kW0;.................'oXWKdlxXNO:.,dXWO:...:ONNx,................,O
ccccccccccccccco0WW0dcccclddddddddocccccoONWWNOocccccccccccccccoKW0lccccccccccccccdKWNOlccccoddddddddlcccccccoONWXxlccccccccccccccl0WKoccccccccccccccxXWNklccccodddddddolcccccxXWNklccccccccccccccccoKWKocccccccccccccclkXWXxlccclodddddddod0WW0occco0WW0occccccccccccclOWK:..................:ONMWNNWW0o,......,dXWKl'....................oNXl..................c0WWWNNWNOc'..'oKWMWNKOo,...................dWXOc..................'oKMWNNNWNk:...:ONWNNNNXOc'..................lXNo..................,xNWWNNWWXx;..,oKNNkloKW0c...................:KWx'.................;kWMWNNWWKo,......c0NWW0o,..................cXWd...................:OWMWNNWW0l'.......'cONNO:..................;0Mk'..................lKWWNNNWNO:'.....,oXWO:.....................,kW0;.................'oXMWNNWWXx;';xNWk;...;kNWk;................,O
cccccccccccccccoONWKdccclxKNNNNNNXklccccloxOKNNKdccccccccccccccoKW0lccccccccccccccd0WN0occclkKNNNNNNKxlccccokKNNKxlcccccccccccccccl0WKoccccccccccccccxXWNOlcccoOXNNNNNNKdcccccxXWNklccccccccccccccccoKWKocccccccccccccclxXWXklccco0XNNNNNN0k0WW0occcd0NNOoccccccccccccclOWK:..................:ONWKxxOXNXd,....,oKWKl'.....................oNXl..................c0WN0xxOXNKo''lKWNOxkKNNx;..................dWXOc..................'oKMNOxx0NN0c'.,lddlclkXW0c..................lXNo..................,xXWXkdkKNNk:;dXWNkc:dXMKl,..................:KWx'.................;kWWKkdkKNXx;.....,:okKNXx;.................cXWd...................:OWW0xxOXNKd,....':xKNXx;...................;0Mk'..................lKWNOdx0NN0l'....'oXWO:.....................,kW0;.................'oXWXOxx0NNOc:xNWk;...;kNWk,................,O
ccccccccccccccclxKWN0dlccoxkO0XWWXxloxkxlcclxKWNOlcccccccccccccoKW0lcccccccccccccclkXWNOoccldkkO0NWWKdcccokKNWXkocccccccccccccccccl0WKoccccccccccccccoONWXkoccldkkOKNMN0occcccxXWNklccccccccccccccccoKWKocccccccccccccccd0NWKxlcclxkk0XWMNOdONWKdcccxXWNOlccccccccccccclOWK:..................:ONNx,.,oXWKl...,oKWKo'......................oNXl..................c0WXd,.;xNWO:;kWNk:.,lKWKl'.................dWXOc..................'oKMKl'':ONNk;'',,'...c0WXo'.................lXNo..................,xNW0:.'c0WXxlOWMWNXXNWMWKo,.................:KWx'.................;kWNk:.,oKWKl;:ol:'..'oXWKl.................cXWd...................:OWNd,.;xXW0c..':dKNNOl'....................;0Mk'..................lKWXo'';kWNk:....'oXWO:.....................,kW0;.................'oXW0c''cOWNx:dXW0c'..c0WNd,................,O
cccccccccccccccclxKNWX0kddddkKNWXkllxXWN0xdxONWXklcccccccccccccoKW0lccccccccccccccclkXWNKOxdodxOKNWKxlcoxKNWWX0kxxdlccccccccccccccl0WKocccccccccccccccoOXWNKOxdodxOXWN0dccccccxXWNklccccccccccccccccoKWKoccccccccccccccccd0NWN0kxdodx0XWNOolxKWNKxdxKWWKdcccccccccccccclOWK:..................:OWW0oldONNO:..,oKWKo'.......................oNXl..................c0WNOolxKWNx;,dXWKd:lkNWOc..................dWXOc..................'oKMXxloxXWXd;:xOOdc:lkNWO:..................lXNo..................,xNWKdlokXWKo:lxxxxxk0NMNkc'.................:KWx'.................;kWW0dldONWOc;dXNKdc:lONNO:.................cXWd...................:OWNOold0WNk;';dKWMN0dllc;'.................;0Mk'..................lKWNkllxKWXd,....'oXWO:.....................,kW0;.................'oXWKxlokXWKo,:ONNOl:lONWOc.................,O
ccccccccccccccccccok0XNNNNNNNNKOdccclxKNWNNNNN0xlccccccccccccccoKW0lccccccccccccccccldkKNNNNNNNNNKkoccoONWWWWWNNNNXxccccccccccccccl0WKoccccccccccccccccldOXNWNNNNNNX0xocccccccdKNXklccccccccccccccccoKWKoccccccccccccccccclx0XNNNNNNNNX0xlccld0NWNNNWN0dlcccccccccccccclOWK:..................:ONWWNNNNKx:...:kXKo'........................oNXl..................c0WWNNNNX0d;..,o0NNNNNXkc'..................dWXOc..................'lKWWNNNNXOo,.,o0XNNXNNKx:'..................lXNo..................,dXWWNNNNKkl'.......,oKW0c'..................:KWx'.................;kNWWNNNNKxc'.;d0NNNXNNKx:'.................cXWd...................:ONWNNNNXKd;'cONWWWWNNNNXk:.................;0Mk'..................lKWWNNNNX0o;.....'oXWO:.....................,kW0;.................'oXWWNNNNXOl,.':kXNNXNNXkc'.................,O
ccccccccccccccccccccloxkkOOkxdocccccccldkkOkxdlccccccccccccccccoKW0lcccccccccccccccccccldxkkOkkxdlccccldxxxxxxxxxxdlccccccccccccccl0WKocccccccccccccccccccodxkkOkkxolcccccccccldxdocccccccccccccccccoKWKoccccccccccccccccccclodxkOOkxdolccccccldxkOkxdlcccccccccccccccclOWK:..................';clllcc:,'....';c:'.........................oNXl..................':clllcc:,.....';codol:,....................dWXOc...................,:llllcc:,.....,:lddoc;'....................lXNo...................;cllllcc;'..........,:c:'...................:KWx'.................';cclllc:;'....';coddoc;'...................cXWd...................':clllcc:,'..,clllllllllc;'.................;0Mk'..................,:clllcc:,........,cc:'.....................,kW0;..................,cllllcc;'.....':loddl:,...................,O
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXOc...............................................................lXNo...............................................................:KWx'.............................................................cXWd...............................................................;0Mk'..............................................................,kW0;.............................................................,O
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXOc...............................................................lXNo...............................................................:KWx'.............................................................cXWd...............................................................;0Mk'..............................................................,kW0;.............................................................,O
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKW0lccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccl0WKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccoKWKocccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclOWK:...............................................................oNXl..............................................................dWXOc...............................................................lXNo...............................................................:KWx'.............................................................cXWd...............................................................;0Mk'..............................................................,kW0;.............................................................,O
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxXWKxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodKWXxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxKWXxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodKWXo;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xNNd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kWX0d;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dNNx;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oXWO:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oXWk:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lKM0c;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;c0MKl;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;c0
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMWNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNWMWNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNWMNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXNNWMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXNWMWXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNWMWNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNWMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNW
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKXWWXK00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0XWMNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKNMWK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KWMNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KNMWK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KNWWNXKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KK0KNMWX0K0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMNK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMXKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KW
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWWKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWWN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMWNKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkOkkkkkkOkkkkkkkkkkkkkkkkkkkOOkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkOkkxl:cokkkkoc:lxkkkxl:coxoc:;:::::::cdkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkdc:cdkOOxo::lxkkkdc:cdkkkkkxoccdkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkoc:lxkkkxl:cokkkkdc:cxkkkoc:;;:;:cdkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkxl::lxkOkdl:cdkkkko::lxkkkkOkd:,,:dkOkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkxl::okkOkdc:cdkOkxl::oxkxdc;,,;coxkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkdc:cdkkkko::lxkOkdl::okkxoc;,,;coxkkkkkkkkkkkkkkkOXMWXKkkkkkkkkOOOkkdc:ldkOkxo::oxkkkdc:cdkkxo:;::lxkOkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkxo::lxkkkxl:cokkkkoc:lxkkdl:,,,:ldkkkOOkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkOkko'  ,dkkd,  .cxOkl. .:d:.         .lkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkko. .:dkko'  .lkkx:. .lkkOkxc. .:xkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkxc. .cxkxc.  'okkd;. 'okOd,      ..lkOkkkkkkkkkkkkONMNOkkkkkkkOkkkkx;. .lkkx:. .;dkko, .,dkkkkxl'   .lkkOkkkkkkkkkkk0NMNOkkkkkkkkkkkkkd,  ,okkd;  .:xOkl. .:xd:.  ..  .;dkOkkkkkkkkkkkkOXMN0kkkkkkkkkkkOko' .;dkko'  .ckkkc. .cxo;.  ..  .;okkkkkkkkkkkkkkOXMWXKkkkkkkOkkkOkkl. .:xkkl.  'okkx:. .lkxc..   .okkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkx:. .lkkxc.  ,dkko,. ,dxc.   .   'lxkOkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkOkkkx:. .lkxc.   'okd;  .okxollll:.  .:xkkkOkkkkkkkkOKWWKOkkkkkkkkkkkkkd,  .okd;.   ;dko'  'dkkkxc. .;dkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkOko'  ,dkd'   .:xkl. .;dkkl. .;lllooxkkkkkkkkkkkkkkONMNOkkkkkkkkkkOkkl.  :xko.   .ckxc. .cxkOkd:.    .lkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkx:. .ckxc.   'okx;  .lxo;'':ll,  .ckOkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkx;  .lkx:.   ,dkd,  'oo,  .:oo;.  ;xkkkkkkkkkkkkkOXMWNKkkkkkkkkkOOkko,  'okd,   .;xkl.  ;dkkdoc'  .lkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkl.  ;dko'   .cxkc. .:dl.  'coc'  .lkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkOkkkko.  ;do'    .:dl.  ;xkkOOkkx:. .:xkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkOxc. .:dl.    .cxc. .cxOkxc.  ,okkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkOkx:. .cdc.    .ld;. .lkkd;. .,cldxkkOOkkkkkkkkkkkkONMNOkkkkkkOOkkkkkd;  'ld;.    ,do,  'okkko,  ..  .lkkkkOkkkkkkkkk0NMNOkkkkkkkkkkkkOko'  ,do,     ;do.  ;dkkkxxdl:.  'okOOkkkkkkkkkkkOXMN0kkkkkkkkkkkkOkl. .;do.    .cdc. .:xdc;:lxkkl.  ,dkkkkkkkkkkkkkOXMWNKkkkkkkkkkkkOkxc. .cdc.    .ld:. .ckkkkOd;  .lkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkd;. .ld:.    'od;  'od;  .lkkkl. .;dkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkOkkkkx;  .:;. ..  .:;. .lkkkkkkx:. .:xkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkd,  'c,  ..  ,c,  'okkx:.   ..,lxkkOkkkkkkkkkkkk0NMXOkkkkkkkkkkkkOkl'  ,c'  ..  ;c.  ,dkkl.      .,okkkkkkkkkkkkkkkONMNOkkkkkkkkkOkkOkc. .;:. ... .;:. .:xkxc.  .:,. .lkkOkkOkkkkkkkk0NMNOkkkkkkkkkkkkkkx:. .:;. ... .:;. .lkkkOkxc.   .cxkOkkkkkkkkkkkkOXMN0kkkkkkkkkkkkOkd;  .c,. ..  'c,  .okkOOOOkxl'  .lkkkkkkkkkkkkkkOXMWNKkkkkkkkkOkkkkko'  'c,  ..  ,c'  ,dkOkkOd;  .okkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkOkl. .;:.  .. .;:.  ;xo'  'okkko'  ,dkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkOkl.  .. .:c'  ..  ;dkkkkkx:. .:xkOkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkc. ... .cc. ... .:xkxc.  ...  .;dkOkkkkkkkkkkkk0NMXOkkkkkkkkkkkkOkx:. ..  'c:. ..  .cxkko;'';:;.  .lkOkkkkkkkkkkkkONMNOkkkkkkOOkkkkkkd,  ..  ,l;. ..  .okd;.  'lo;. .cxkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkko.  .. .;l'  ..  ,dkkOkkkd:,.  .:xkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkxl. ... .:c.  .. .;dkOkkkko;.  'lkkOkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkx:. ... .c:. ... .cxkkkkOd;  .okkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkd,  ..  'l;. ..  .lko'  'dkkkd'  'dkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkd;     'oxc.    .ckkOkkx:. .:dkkOkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkko'     ;dd;.    'okko'  'oxd;. .lkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkOkkl.    .:xo'     ,dkkkxxxxkOx:. .:xkkkkkkkkkkkkkONMNOkkkkkkkkkkkkOkxc.    .cxo.    .;xkc.   ...    .:xkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkOkd;.    'oxc.    .cxkxolldkkkd;  .lxOOkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkd,     ,dx:.    .lkkkkkd:.  .:dkkkkkkkkkkkkkkkkOXMWX0kkkkkkkkkkkkOkko'    .;dd,     'okkkkkkd;  .okkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkxc.    .cxo'     ;dkd,  .lkkkl. .;dkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkc.   .cxko,    ,dkkkkx:. .;dkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkx:.   .lkko.    :xkkd,  .col,  .okkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkd;.   'okxc.   .cxkxl,',codl'  .lkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkko'    ;dkx:.   .lkko;'......   .cxkkkkOkkkkkkk0NMNOkkkkkkkkkkkkkkOkl.   .:xkd,    'dkko,. .cddl'  .lkOkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkxc.   .ckko'    ,dOkkd:.   .:loodkkkkkkkkkkkkkkOXMWNKkkkkkkkkkkkkkkkx;.   'okkl.   .:xOkkkkOd;  .lkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkd,    ,dkx:.   .lkOxc.  ,ldl'  .lkOkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkd,   ,dkkxc.  .cxkOkkl. .;dkOkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkko.  .;dkOx:.  .lkOkko,.  ..  .cxkOOkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkl.  .cxkkd,   ,okOko,.  ..   'cxkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkOx:.  .lkkko'   ;xkkkxxxxxxd;  .cxkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkd;   'okOkl.  .:xOkkl'.  ..   'lxkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkOkd'   ;dkkxc.  .lkkxl.         .,dkkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkOkl.  .:xkkx;.  'okkkkkkkd;  .lkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkOxc.  .cxOko,   ,dkOkxc.   .   .cxkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkko:;cokOkkxl::cdkkkkkdl:cdkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkxo:;cdkkkkdl;:lxkOkkkxl:,',;cdkOkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkxl::lxkkOkdc::okkkkkxo:;'',:ldkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkdc;:lxkkkko::cokkkkkkkkkkko::cdkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkoc::okkOkxl::cdkkkkkxl:,'',:ldkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkOkko::cdkkkkdl::lxkkko:;;;;;;;;;;lxkkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkkkxl::cdkkkkdc::lxkkOOkkkxo::cxkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkOkkdl::lxkkkkoc;cokkkkkkdc;,',;cdkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkOOOOkkkkkOOOOkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkOOOOOkkOkOOOOOOkkkkkkkkkkkkkkkkkOkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkOOkOkkOOkOOOOkkkkkkkOkkkxkkkkkkkkkkkkkkkkkkkkONMNOkkkkkkkkkkkkkkkkOOOOOkkkkkOOOOkkkkkkkkkkkkkkOOkkkkkOkkkkkkkkk0NMNOkkkkkkkkkkkkkkkkkkOOOkkkkkOOOOOOkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kOkkkkkkkkkkkkOkkOOOOOkkkkkOOOOkkOkOOOOOOOOOOOOOOOkkkkkkkkkkkkOXMWXKkkkkkkkkkkkkkkkkkkOOOkkkkkOOOOOkkkkkkkkkkOOOOkkkkkkkkkkkkkkkkOXMN0kkkkkkkkkkkkkkkkkOOOOOkkkkOOOOOkkkkkkkkkkkxkkkOkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkKWWKOkOkkkkkkkkkkkkkkkkkOOOOkkkOkkkkkkkkkkkkOkkkkkkOkkOkkkkkkkkkkOk0NMXOkkkkkkkkkkOkkkkOkkkkkOOkkkkOOkkkOkkkkOkkkkOOkkkkkkkkkkkkkkkkkkONMNOkkkOkkkkkkkkkkkkOOkkkkkkkkkkOkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkk0NMNOkkkkkkkkkkkkkkkOkkOOkkkkkkkkkOOkkkkkkkkkOkkkOkkkkkkkkkkkkkkkkkOXMN0kOkkkkkkkkkkkkOkkkkkkkkkkOOOkkOOkkkkkkOkkkkkkkkkkkkkkkkkkkkOkkOXWWN0kkkkkkkkkkkkkkkkkkkOOOkkkkkkkkOkkOkkOkkkkkkOOkkkkkkkkkkkkkkkkOXMW0kOkkOkkkkkkkkkkOkkOOkkOkkkOkkOOkkkkkkkkOOkkkkkOkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOk0WWXOkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0N
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkKWWKOkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkONMNOkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMN0kOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWWXKkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkOXMW0kkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkk0WWXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOk0N
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMWWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/



struct Color{
	uint8_t red;
	uint8_t green;
	uint8_t blue;
	uint8_t warm;
};

struct Color int_to_rgbw(int color){
		
		struct Color rgbw = {0, 0, 0, 0};
		rgbw.green = 	(color & 0xFF000000)>>24;
    rgbw.red = 		(color & 0x00FF0000)>>16;
    rgbw.blue = 	(color & 0x0000FF00)>>8;
    rgbw.warm = 	color & 0xFF;

    return rgbw;
}

void get_bites(int color, uint8_t *bites){
	struct Color rgbw = {0, 0, 0, 0};
	rgbw = int_to_rgbw(color);
	
	for (uint8_t co = 0; co<8; co++){
		bites[co] 		= 	(rgbw.green>>(7-co));
		bites[co+8] 	= 	(rgbw.red>>(7-co));
		bites[co+16] 	= 	(rgbw.blue>>(7-co));
		bites[co+24] 	= 	(rgbw.warm>>(7-co));
	}
}

//void fill_buffer(int color, uint8_t lower, uint8_t upper){

//	for(uint8_t i = 0; i<lower*32; i++){
//		BUF_DMA[i] = LOW;
//	}

//	struct Color rgbw = {0, 0, 0, 0};
//	rgbw = int_to_rgbw(color);

//	uint8_t rgbw_array[4] = {rgbw.green, rgbw.red, rgbw.blue, rgbw.warm};
//	
//// First step - pixels
//	for(uint16_t pixel = 1; pixel<=upper-lower; pixel++){
//// Second step - elemental colors (RGBW)
//		for(uint8_t color = 1; color<=4; color++){
//			for(uint8_t bite_number = 1; bite_number<=8; bite_number++){
//				uint8_t bit = rgbw_array[color]>>(7-bite_number);
//				if(bit){
//					BUF_DMA[lower*32+pixel*color*bite_number] = HIGH;
//				}
//				else{
//					BUF_DMA[lower*32+pixel*color*bite_number] = LOW;
//				}
//			}
//		}
//	}
//	
//	for(uint16_t i = ARRAY_LEN - DELAY_LEN; i<ARRAY_LEN; i++){
//		BUF_DMA[i] = LOW;
//	}
//}

uint8_t get_level(uint8_t bite){
	if(bite){
		return HIGH;
	}
	else{
		return LOW;
	}
}

void fill_buffer(int color, uint8_t lower, uint8_t upper){

	uint8_t bites[32];
	get_bites(color, bites);
	
	for(uint16_t pixel = lower; pixel<upper; pixel++){
		for(uint8_t bite = 0; bite<32; bite++){
			BUF_DMA[pixel*32 + bite] = get_level(bites[bite]);
		}

	}
	
	if(lower!=0){
		for(uint8_t i = 0; i<lower*32; i++){
			BUF_DMA[i] = LOW;
		}		
	}

	
	for(uint16_t i = upper*32; i<ARRAY_LEN-DELAY_LEN; i++){
		BUF_DMA[i] = LOW;
	}
}





//void send_bite(uint8_t bite){
//    if(bite){
//        HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_SET);
//        for(int i = 0; i<10; i++){}

//        HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_RESET);
//        for(int i = 0; i<8; i++){}
//    }

//    else{
//        HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_SET);
//        for(int i = 0; i<8; i++){}

//        HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_RESET);
//        for(int i = 0; i<10; i++){}
//    }
//}

//void end_of_message(void){
//    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_RESET);
//    for(int i = 0; i<1500; i++){}
//}



//void send_pixel(int color){
//	
//		struct Color rgbw = {0, 0, 0, 0};
//		rgbw = int_to_rgbw(color);

//    for (uint8_t co = 0; co<8; co++){
//        send_bite(rgbw.green>>(7-co));
//    }
//		
//    for (uint8_t co = 0; co<8; co++){
//        send_bite(rgbw.red>>(7-co));
//    }
//		
//    for (uint8_t co = 0; co<8; co++){
//        send_bite(rgbw.blue>>(7-co));
//    }
//		
//    for (uint8_t co = 0; co<8; co++){
//        send_bite(rgbw.warm>>(7-co));
//    }
//}

//void send_word(uint8_t green, uint8_t red, uint8_t blue, uint8_t warm){

//}

//int rgbw_to_int(uint8_t green, uint8_t red, uint8_t blue, uint8_t warm){
//    int rgbw_united = 0;
//    rgbw_united = rgbw_united | ((int) green<<24);
//    rgbw_united = rgbw_united | ((int) red<<16);
//    rgbw_united = rgbw_united | ((int) blue<<8);
//    rgbw_united = rgbw_united | ((int) warm);

//    return rgbw_united;
//}

//void fill_color(uint8_t green, uint8_t red, uint8_t blue, uint8_t warm, uint8_t low, uint8_t high){
//    
//    int color = rgbw_to_int(green, red, blue, warm);

//    for(uint8_t i = 0; i<low; i++){
//      send_pixel(0);
//    }

//    for(uint8_t i = low; i<high; i++){
//      send_pixel(color);
//    }

//    end_of_message();
//}


//void clear_strip(void){
//    for(int i = 0; i<1500; i++){
//      send_pixel(0);
//    }

//    end_of_message();
//}

////void fill_strip(void){
////    for(uint8_t i = 0; i < number_of_leds; i++){
////        send_pixel(leds[i]);
////    }

////    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_RESET);
////    for (int i = 0; i<1500; i++){}
////}

